name: tests

on:
  push:
    branches: [main, numpy-params, test-me-*]
#    tags:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    timeout-minutes: 10

    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          python: '3.11'
          tox_env: py311
        - os: ubuntu-latest
          python: '3.12'
          tox_env: py312
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Get pip cache dir
        id: pip-cache-dir
        run: echo "PIP_CACHE_DIR=$(pip cache dir)" >> $GITHUB_ENV

      - name: Use pip cache
        id: pip-cache
        uses: actions/cache@v4
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: tests-${{ matrix.os }}-pip-${{ matrix.python }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            tests-${{ matrix.os }}-pip-${{ matrix.python }}-

      - name: Install Packages
        run: python -mpip install --upgrade pip tox

      - name: Run Tox
        run: |
          tox -e ${{ matrix.tox_env }} -- -vv -s

      - name: Run Coveralls
        run: |
          pip install coveralls
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

